{ lib, config, ... }:

let
  defaultCoreSecrets = [
    { name = "OBSIDIAN_API_KEY"; path = "op://Private/Obsidian.md/api key"; }
    { name = "LANGUAGETOOL_USERNAME"; path = "op://Private/LanguageTool/username"; }
    { name = "LANGUAGETOOL_API_KEY"; path = "op://Private/LanguageTool/api key"; }
  ];

  coreSecrets = config.secrets.coreSecrets;
  extraSecrets = config.secrets.extraSecrets or [ ];
  allSecrets = coreSecrets ++ extraSecrets;

  secretNames = map (s: s.name) allSecrets;
  secretNamesStr = lib.concatStringsSep "|" secretNames;

  secretFetchLines = map (secret: ''
    value=$(op read '${secret.path}' 2>/dev/null || true)
    if [[ -n "$value" ]]; then
      new_secrets["${secret.name}"]="$value"
    fi
  '') allSecrets;

in {
  options.secrets = {
    coreSecrets = lib.mkOption {
      type = lib.types.listOf (lib.types.submodule {
        options = {
          name = lib.mkOption {
            type = lib.types.str;
            description = "Environment variable name";
          };
          path = lib.mkOption {
            type = lib.types.str;
            description = "1Password item path (op://...)";
          };
        };
      });
      default = defaultCoreSecrets;
      description = "Core secrets to fetch from 1Password (can be overridden)";
    };

    extraSecrets = lib.mkOption {
      type = lib.types.listOf (lib.types.submodule {
        options = {
          name = lib.mkOption {
            type = lib.types.str;
            description = "Environment variable name";
          };
          path = lib.mkOption {
            type = lib.types.str;
            description = "1Password item path (op://...)";
          };
        };
      });
      default = [ ];
      description = "Extra secrets to fetch from 1Password (extends coreSecrets)";
    };
  };

  config.home.file.".local/bin/refresh-secrets" = {
    executable = true;
    text =
      let
        scriptBody = ''
          #!/usr/bin/env bash
          # Auto-generated by Nix - do not edit manually

          set -eo pipefail

          SECRETS_FILE="$HOME/.config/shell/secrets.env"
          SECRETS_PATTERN="${secretNamesStr}"
          OP_SOCKET=""

          case "$(uname)" in
            Darwin) OP_SOCKET="~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock" ;;
            Linux)  OP_SOCKET="$HOME/.1password/agent.sock" ;;
          esac

          if [[ -e "$OP_SOCKET" ]]; then
            :
          else
            OP_SOCKET=""
          fi

          if ! command -v op >/dev/null 2>&1 || [[ -z "$OP_SOCKET" ]]; then
            exit 0
          fi

          mkdir -p "$(dirname "$SECRETS_FILE")"

          declare -A new_secrets
          '' + lib.concatStrings secretFetchLines + ''
          if [[ ''${#new_secrets[@]} -gt 0 ]]; then
            {
              if [[ -f "$SECRETS_FILE" ]]; then
                grep -vE "^($SECRETS_PATTERN)=" "$SECRETS_FILE" 2>/dev/null || true
              fi

              for key in "''${!new_secrets[@]}"; do
                echo "export $key=\"''${new_secrets[$key]}\""
              done
            } > "$SECRETS_FILE.tmp"

            mv "$SECRETS_FILE.tmp" "$SECRETS_FILE"
            chmod 600 "$SECRETS_FILE"
          fi
        '';
      in scriptBody;
  };
}